### ISSUE TITLE
Please add usage instructions

### ISSUE THREAD

**Issue by unixorn** [Cellophan/czsh#2]
It's unclear from the readme exactly how you would use this - if it's running in a container, what arguments should you pass to it so that it can access the other applications on your machine? And are you going to lose your command history when the container exits?

**Comment by cell** [comment]
Will do. Damned. One person saw this project!

**Comment by unixorn** [comment]
I maintain the [awesome-git-plugins](https://github.com/unixorn/awesome-zsh-plugins) list, so I look for new plugins and themes every couple of days 😄

**Comment by cell** [comment]
@unixorn Would this be ok: https://github.com/Cellophan/czsh/pull/3 ?

BTW, if you are using vim, I should also create a README.md for https://github.com/Cellophan/cvim

**Comment by cell** [comment]
Merged and built by docker hub.
